PipelineSecrets:
  DockerConfig: '{"auths":{"ApexCluster.azurecr.io":{"auth":"QXBleENsdXN0ZXI6NHdMN2NXY1Yza0U1bzQwK2Y1RXE1QXY2cHZjVjA4VzQ="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 40.114.86.175.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: ApexCluster.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
